<?php

namespace Aventura\Diary\Bookable\Availability\Timetable\Rule;

use \Aventura\Diary\DateTime;
use \Aventura\Diary\DateTime\Day;
use \Aventura\Diary\DateTime\Period;
use \PHPUnit_Framework_TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-24 at 13:37:55.
 */
class DotwTimeRangeRuleTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var DotwRangeRule
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DotwTimeRangeRule(Day::MONDAY, Day::FRIDAY,
                DateTime::fromString('15:00', 0), DateTime::fromString('19:00', 0));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    public function testDummy()
    {
        $this->assertTrue(true);
    }
    
    protected function assertObeys($obeys, $start, $duration)
    {
        $period = new Period($start, $duration);
        $this->assertEquals($obeys, $this->object->obeys($period));
    }
    
}
